### ISSUE TITLE
operator went crash after startup

### ISSUE THREAD

**Issue by evetony** [chaosblade-io/chaosblade-operator#12]
first of all, I was using the 0.4.0version and the operator went crash when I tried to operate the cmd like "create k8s node-process stop  --evict-percent 0", it returns a failure and after that, all the command went wrong, and the status of operator becomes "CrashLoopBackOff"

I tried to delete the crd, but it looks like went into a deadlock, only if I patched crd with {"metadata":{"finalizers":[]}} 

after that, I clean the image and install again and again, all went into the status "CrashLoopBackOff"
these are the two snapshot of the logs when the container  went crash
<img width="910" alt="MacHi 2020-02-10 15-13-46" src="https://user-images.githubusercontent.com/30700321/74300780-dd7d7100-4d8b-11ea-9be4-4e9cfceaea8d.png">
<img width="909" alt="MacHi 2020-02-10 15-14-15" src="https://user-images.githubusercontent.com/30700321/74300795-e706d900-4d8b-11ea-9690-01ca6b260093.png">

**Comment by xcaspar** [comment]
@evetony The reason for the problem is that the evict-percent value of 0 was not handled. Please recover the chaosblade operator as follows:
1. Delete the error chaosblade resource:
```
kubectl delete blade xxxxxxx
```
2. Patch or edit the error chaosblade resource to delete the `finalizer.chaosblade.io` in `metadata.finalizers`
```
kubectl edit blade xxxxxxx
```
3. Delete the chaosblade operator pod and the pod will be re-created:
```
kubectl delete pod chaosblade-operator -n kube-system
```

I will fix the issue in the next version, thank you.

**Comment by evetony** [comment]
I do delete chaosblade operator pod and execute the command "helm del --purge" before but it turns out to be useless.
Is that meant what I created would continue to run when I re-install the chaosblade operator if the operation before went wrong or not successfully finnished?

And is the command "kubectl delete blade xxxxxxx" equals to "kubectl delete chaosblade xxx" or "blade destroy <UID>"

**Comment by xcaspar** [comment]
@evetony Requeue is triggered when:
* The operator crash.
* Add `finalizer.chaosblade.io` failed.
* Delete `finalizer.chaosblade.io` failed.
* The experiment has been executed, but the status update failed.

So the current might be due to operator crash.

All of`kubectl delete blade xxxxxxx`, `kubectl delete chaosblade xxx` and `blade destroy` mean that stop and delete the experiment. But kubectl and blade only delete experiments created by themselves.

**Comment by evetony** [comment]
OK, I got it, tks
