### ISSUE TITLE
Why my "evict-percent" option doesn't work

### ISSUE THREAD

**Issue by evetony** [chaosblade-io/chaosblade-operator#14]
Hi, I found the "evict-percent" option doesn't work in my node experiment and pod experiment in the k8s cluster.

No matter what it is, it seems different to my imagination. When I use the "evict-count" option in a node experiment, it will result in the particular number of nodes in the listed node list. But when it comes to the "evict-percent" option, all the listed nodes were executing the experiment. Same as the pod experiment.
By the way I'm still using the 0.4.0 version.

One more thing here is I found the result of "evict-count" is always in an order, could it be more randomly? Or give me another option to lead out an random result when I use the "evict-count" option?

**Comment by xcaspar** [comment]
@evetony I am very sorry to reply so late. The problem that `evict-percent` does not take effect is caused by bug. We will fix it as soon as possible and release it next week. chaosblade-io/chaosblade#306

The suggestion for random selection is very good. We will add the '--random' parameter to implement the feature. chaosblade-io/chaosblade#307

Thank you.
